version: "3.8"

volumes:
  database: {}

services: 
  web:
    image: nyumba_php
    depends_on: [php]
    command: /root/.symfony/bin/symfony server:start
    ports: [9098:8000]
    working_dir: /opt/project
    volumes:
      - ./:/opt/project

  php:
    image: nyumba_php
    build: .docker/php/
    working_dir: /opt/project
    volumes: 
      - ./:/opt/project

  database:
    image: postgres:13
    environment: 
      POSTGRES_DB: nyumba
      POSTGRES_USER: nyumba
      POSTGRES_PASSWORD: nyumba
    volumes:
      - database:/var/lib/postgresql/data:rw

  meilisearch:
    image: getmeili/meilisearch:latest
    ports: [7700:7700]
